"""PR description template loading and section builders."""

import re
from pathlib import Path
from typing import Any

from ogd_to_lod.logging import get_logger

logger = get_logger(__name__)

# Maximum characters for the RDF preview section
_RDF_PREVIEW_MAX_CHARS = 2000

# ---------------------------------------------------------------------------
# Placeholder registry
# ---------------------------------------------------------------------------
# Maps lowercased placeholder text → canonical key + type (inline | block).

_PLACEHOLDER_REGISTRY: dict[str, dict[str, str]] = {
    "dataset name": {"key": "dataset_name", "type": "inline"},
    "dataset description": {"key": "dataset_description", "type": "inline"},
    "csv source": {"key": "csv_source", "type": "inline"},
    "context files": {"key": "context_files", "type": "inline"},
    "base uri": {"key": "base_uri", "type": "inline"},
    "mapping decisions": {"key": "mapping_structure", "type": "block"},
    "csv sample": {"key": "csv_preview", "type": "block"},
    "rdf sample": {"key": "rdf_preview", "type": "block"},
}

# ---------------------------------------------------------------------------
# Default (fallback) template – minimal, no example content
# ---------------------------------------------------------------------------

_DEFAULT_TEMPLATE = """\
## RML Mapping: {{Dataset Name}}

{{Dataset Description}}

### Source Information
- **CSV Source:** {{CSV Source}}
- **Context/Metadata Files:** {{Context Files}}
- **Base URI:** {{Base URI}}

### Mapping Structure

{{Mapping Decisions}}

### CSV Preview

{{CSV Sample}}

### RDF Preview

{{RDF Sample}}

---
_Generated by [OGD to LOD](https://github.com/redlink-gmbh/ogd-to-lod)_
"""

# Regex matching a single {{...}} token (non-greedy)
_PLACEHOLDER_RE = re.compile(r"\{\{(.+?)\}\}")

# Boundaries that terminate a block placeholder's example content
_BLOCK_BOUNDARY_RE = re.compile(r"^(###\s|---)", re.MULTILINE)


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------


def render_pr_template(template_text: str, data: dict[str, str]) -> str:
    """Render a ``{{placeholder}}`` template with the supplied *data*.

    Processing rules
    ~~~~~~~~~~~~~~~~
    * Each ``{{Name}}`` or ``{{Name|default}}`` token is looked up in
      :data:`_PLACEHOLDER_REGISTRY`.
    * **Inline** placeholders: the ``{{…}}`` token is replaced with
      ``data[key]``, or the default if given, or the empty string.
    * **Block** placeholders: the ``{{…}}`` token **and** all content below
      it until the next ``###`` or ``---`` boundary is replaced with
      ``data[key]``.  If no data is supplied, the ``{{…}}`` line is removed
      but the example content is kept.
    * Unregistered placeholders: use the default (after ``|``) if present,
      otherwise leave the ``{{…}}`` token as-is.
    """
    # Collect all matches first
    matches = list(_PLACEHOLDER_RE.finditer(template_text))

    # Process last-to-first so earlier offsets stay valid
    result = template_text
    for match in reversed(matches):
        raw_content = match.group(1)
        # Split on first '|' → key_part, default_value
        if "|" in raw_content:
            key_part, default_value = raw_content.split("|", 1)
        else:
            key_part, default_value = raw_content, None

        lookup = key_part.strip().lower()
        registry_entry = _PLACEHOLDER_REGISTRY.get(lookup)

        if registry_entry is None:
            # Unregistered placeholder
            if default_value is not None:
                result = result[: match.start()] + default_value + result[match.end() :]
            # else leave as-is
            continue

        canonical_key = registry_entry["key"]
        ph_type = registry_entry["type"]
        value = data.get(canonical_key)

        if ph_type == "inline":
            replacement = value if value is not None else (default_value if default_value is not None else "")
            result = result[: match.start()] + replacement + result[match.end() :]
        else:
            # Block placeholder
            result = _replace_block(result, match, value)

    return result


def _replace_block(text: str, match: re.Match, value: str | None) -> str:
    """Replace a block placeholder + its example content, or just remove the tag line."""
    token_start = match.start()
    token_end = match.end()

    # Find the next block boundary (### or ---) after the token
    boundary = _BLOCK_BOUNDARY_RE.search(text, token_end)
    block_end = boundary.start() if boundary else len(text)

    if value is not None:
        # Replace token + all example content with value
        # Find the start of the line containing the token
        line_start = text.rfind("\n", 0, token_start)
        line_start = line_start + 1 if line_start != -1 else 0

        replacement = value + "\n\n"
        return text[:line_start] + replacement + text[block_end:]
    else:
        # No data: remove just the {{…}} line, keep example content
        line_start = text.rfind("\n", 0, token_start)
        line_end = text.find("\n", token_end)
        if line_end == -1:
            line_end = len(text)
        else:
            line_end += 1  # include the newline

        return text[:line_start + 1 if line_start != -1 else 0] + text[line_end:]


# ---------------------------------------------------------------------------
# Template loading
# ---------------------------------------------------------------------------


def load_pr_template(path: str | Path | None = None) -> str:
    """Load the PR description template from a file, falling back to the built-in default.

    Args:
        path: Optional path to a custom template file.

    Returns:
        Template text as a plain string.
    """
    if path is not None:
        template_path = Path(path)
        if template_path.is_file():
            logger.debug("Loading PR template from %s", template_path)
            return template_path.read_text(encoding="utf-8")
        logger.warning("PR template not found at %s — using default", template_path)

    return _DEFAULT_TEMPLATE


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def build_mapping_structure_section(
    mapping_proposal: Any | None = None,
    mapping_decisions: str | None = None,
) -> str:
    """Build the mapping-structure content for the PR description.

    The ``### Mapping Structure`` heading is now part of the template
    itself — this function only returns the body.

    Args:
        mapping_proposal: A ``MappingProposal`` instance (or None).
        mapping_decisions: Optional AI-generated decision summary.

    Returns:
        Formatted markdown string (may be empty).
    """
    if not mapping_proposal:
        return ""

    lines: list[str] = []

    if mapping_decisions:
        lines.append(mapping_decisions)
        lines.append("")

    if mapping_proposal.dimensions:
        lines.append("**Dimensions:**")
        for dim in mapping_proposal.dimensions:
            dim_str = f"- `{dim.column}` ({dim.dimension_type})"
            if dim.granularity:
                dim_str += f" - granularity: {dim.granularity}"
            if dim.hierarchy:
                dim_str += f" - hierarchy: {dim.hierarchy}"
            lines.append(dim_str)
        lines.append("")

    if mapping_proposal.measures:
        lines.append("**Measures:**")
        for measure in mapping_proposal.measures:
            measure_str = f"- `{measure.column}`"
            if measure.unit:
                measure_str += f" ({measure.unit})"
            if measure.aggregation:
                measure_str += f" - aggregation: {measure.aggregation}"
            lines.append(measure_str)

    return "\n".join(lines)


def build_rdf_preview_section(rdf_preview: str | None = None) -> str:
    """Build the RDF preview content for the PR description.

    The ``### RDF Preview`` heading is now part of the template — this
    function only returns the code-block body.

    Args:
        rdf_preview: RDF Turtle output from validation.

    Returns:
        Formatted markdown string (may be empty).
    """
    if not rdf_preview:
        return ""

    truncated = rdf_preview[:_RDF_PREVIEW_MAX_CHARS]
    suffix = ""
    if len(rdf_preview) > _RDF_PREVIEW_MAX_CHARS:
        suffix = "\n... (truncated)"

    return f"```turtle\n{truncated}{suffix}\n```"


def build_csv_preview_section(csv_schema: dict[str, Any] | None = None) -> str:
    """Build a markdown table from CSV schema data.

    Renders column names as headers and ``sample_rows`` as table rows.

    Args:
        csv_schema: Parsed CSV schema dict with ``columns`` and ``sample_rows``.

    Returns:
        Formatted markdown table string (may be empty).
    """
    if not csv_schema:
        return ""

    columns = csv_schema.get("columns", [])
    if not columns:
        return ""

    col_names = [col["name"] for col in columns]

    sample_rows = csv_schema.get("sample_rows", [])
    if not sample_rows:
        return ""

    # Header
    header = "| " + " | ".join(col_names) + " |"
    separator = "| " + " | ".join("---" for _ in col_names) + " |"

    # Rows
    row_lines: list[str] = []
    for row in sample_rows:
        cells = [str(row.get(name, "")) for name in col_names]
        row_lines.append("| " + " | ".join(cells) + " |")

    return "\n".join([header, separator, *row_lines])
