"""PR description template loading and section builders."""

from pathlib import Path
from string import Template
from typing import Any

from ogd_to_lod.logging import get_logger

logger = get_logger(__name__)

_DEFAULT_TEMPLATE = """\
## RML Mapping: ${mapping_name}

${data_sources}

${dcat_section}

${mapping_structure}

${rdf_preview_section}

---
_Generated by [OGD to LOD](https://github.com/redlink-gmbh/ogd-to-lod)_
"""

# Maximum characters for the RDF preview section
_RDF_PREVIEW_MAX_CHARS = 2000


def load_pr_template(path: str | Path | None = None) -> Template:
    """Load the PR description template from a file, falling back to the built-in default.

    Args:
        path: Optional path to a custom template file.

    Returns:
        A ``string.Template`` ready for ``safe_substitute()``.
    """
    if path is not None:
        template_path = Path(path)
        if template_path.is_file():
            logger.debug("Loading PR template from %s", template_path)
            return Template(template_path.read_text(encoding="utf-8"))
        logger.warning("PR template not found at %s — using default", template_path)

    return Template(_DEFAULT_TEMPLATE)


def build_data_sources_section(
    csv_path: str | None = None,
    dcat_path: str | None = None,
    base_uri: str | None = None,
) -> str:
    """Build the data-sources section of the PR description.

    Args:
        csv_path: Path to the CSV file.
        dcat_path: Path to the DCAT metadata file.
        base_uri: Base URI for generated resources.

    Returns:
        Formatted markdown string (may be empty).
    """
    lines: list[str] = []
    if csv_path:
        lines.append(f"**CSV Source:** `{csv_path}`")
    if dcat_path:
        lines.append(f"**DCAT Metadata:** `{dcat_path}`")
    if base_uri:
        lines.append(f"**Base URI:** `{base_uri}`")
    return "\n".join(lines)


def build_dcat_section(dcat_metadata: dict[str, Any] | None = None) -> str:
    """Build the DCAT metadata section of the PR description.

    Args:
        dcat_metadata: Parsed DCAT metadata dictionary.

    Returns:
        Formatted markdown string (may be empty).
    """
    if not dcat_metadata:
        return ""

    lines: list[str] = []
    if dcat_metadata.get("title"):
        lines.append(f"**Dataset Title:** {dcat_metadata['title']}")
    if dcat_metadata.get("description"):
        desc = dcat_metadata["description"]
        if len(desc) > 200:
            desc = desc[:200] + "..."
        lines.append(f"**Description:** {desc}")
    return "\n".join(lines)


def build_mapping_structure_section(mapping_proposal: Any | None = None) -> str:
    """Build the mapping-structure section of the PR description.

    Args:
        mapping_proposal: A ``MappingProposal`` instance (or None).

    Returns:
        Formatted markdown string (may be empty).
    """
    if not mapping_proposal:
        return ""

    lines: list[str] = []

    if mapping_proposal.dimensions:
        lines.append("### Mapping Structure")
        lines.append("")
        lines.append("**Dimensions:**")
        for dim in mapping_proposal.dimensions:
            dim_str = f"- `{dim.column}` ({dim.dimension_type})"
            if dim.granularity:
                dim_str += f" - granularity: {dim.granularity}"
            if dim.hierarchy:
                dim_str += f" - hierarchy: {dim.hierarchy}"
            lines.append(dim_str)
        lines.append("")

    if mapping_proposal.measures:
        if not lines:
            lines.append("### Mapping Structure")
            lines.append("")
        lines.append("**Measures:**")
        for measure in mapping_proposal.measures:
            measure_str = f"- `{measure.column}`"
            if measure.unit:
                measure_str += f" ({measure.unit})"
            if measure.aggregation:
                measure_str += f" - aggregation: {measure.aggregation}"
            lines.append(measure_str)

    return "\n".join(lines)


def build_rdf_preview_section(rdf_preview: str | None = None) -> str:
    """Build the RDF preview section of the PR description.

    The preview is truncated to ``_RDF_PREVIEW_MAX_CHARS`` characters.

    Args:
        rdf_preview: RDF Turtle output from validation.

    Returns:
        Formatted markdown string (may be empty).
    """
    if not rdf_preview:
        return ""

    truncated = rdf_preview[:_RDF_PREVIEW_MAX_CHARS]
    suffix = ""
    if len(rdf_preview) > _RDF_PREVIEW_MAX_CHARS:
        suffix = "\n... (truncated)"

    return (
        "### RDF Preview\n\n"
        f"```turtle\n{truncated}{suffix}\n```"
    )
